server.port=${PORT:8080}
spring.data.mongodb.uri=${MONGODB_URI:mongodb+srv://collabrix_user:mmmmmmmm@cluster0.2i10uvd.mongodb.net/collabrix?retryWrites=true&w=majority&appName=Cluster0}
de.flapdoodle.mongodb.embedded.version=6.0.8
python.service.url=${PYTHON_SERVICE_URL:http://localhost:5000}
jwt.secret=${JWT_SECRET:9a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d99a4f2c8d3b7a1e6f45c8a0b3f267d8b1d4e6f3c8a9d2b5f8e3a9c8b5f6v8a3d9}
jwt.expirationMs=86400000
spring.autoconfigure.exclude=${SPRING_AUTOCONFIGURE_EXCLUDE:de.flapdoodle.embed.mongo.spring.autoconfigure.EmbeddedMongoAutoConfiguration}
